name: Daily Build

on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - run: go install honnef.co/go/tools/cmd/staticcheck@latest
      - run: ./checks.sh

      - run: make cache
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

      - name: Get build date
        id: date
        run: echo "date=$(date +%d-%m-%Y)" >> "$GITHUB_OUTPUT"

      - uses: snapcore/action-build@v1
        id: build
        env:
          REVMAP_BUILD_DATE: ${{ steps.date.outputs.date }}

      - uses: snapcore/action-publish@v1
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: edge
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
